#
# strings.py
#

STR_ALARM_DOOR_DESC = ""
STR_ALARM_DOOR_SPEECH = ""
STR_ALARM_WINDOW_DESC = ""
STR_ALARM_WINDOW_SPEECH = ""
STR_ALARM_FLOOD_DESC = ""
STR_ALARM_FLOOD_SPEECH = ""
STR_ALARM_TEMP_DESC = ""
STR_ALARM_TEMP_SPEECH = ""
